#!/usr/bin/perl
use lib '/var/www/okmis/src/lib';

#use DateTime;
use DBUtil;

sub first_day_of_week {
    my ( $year, $week ) = @_;

    # Week 1 is defined as the one containing January 4:
    my $dt =
      DateTime->new( year => $year, month => 1, day => 4 )
      ->add( weeks => ( $week - 1 ) )
      ->truncate( to => 'week' )
      ->subtract( days => 1 );    # to get Sunday.
    my $mon = length( $dt->month ) == 1 ? '0' . $dt->month : $dt->month;
    my $day = length( $dt->day ) == 1   ? '0' . $dt->day   : $dt->day;
    my $d   = $year . '-' . $mon . '-' . $day;
    return ($d);
}

# Find first day of second week of 2012 (2012-01-09):
my $d = DBUtil->SundayOfWeek( 2014, 44 );

print "$d\n";
