#!/usr/bin/perl 
use lib 'C:/xampp/htdocs/src/lib';
use DBI;
use myDBI;
use Accounts;
use Time::Local;
my $DT = localtime();

#############################################################################
my @DBS =
    $ARGV[0] eq 'test' ? Accounts->dbs('test')
  : scalar(@ARGV)      ? @ARGV
  :                      Accounts->dbs('active');

print qq|${DT}\nAgencies and Clinics\n|;
print qq|Type DB-ProvID\tName\n|;
foreach my $dbname (@DBS) {
    my $dbh = myDBI->dbconnect($dbname);
    my $sAgency =
      $dbh->prepare("select ProvID,Name from Provider where ProvID=?");
    my $sClinics = $dbh->prepare(
"select ProvID,Name,ManagerID from Provider left join Manager on Manager.ProviderID=Provider.ProvID where Active=1 and Type=3 order by Name"
    );
    my $sClient = $dbh->prepare(
"select ClientID,FName,LName from Client where clinicClinicID=? order by LName,FName"
    );

    my $Prev_AgencyID = '';
    $sClinics->execute();
    while ( my $rClinics = $sClinics->fetchrow_hashref ) {
        my $AgencyID = $rClinics->{ManagerID};
        if ( $AgencyID ne $Prev_AgencyID ) {
            $sAgency->execute($AgencyID);
            my $rAgency = $sAgency->fetchrow_hashref;
            print qq|Agency: ${dbname}-${AgencyID}\t$rAgency->{'Name'}\n|;
            $Prev_AgencyID = $AgencyID;
        }
        print
          qq|  Clinic: ${dbname}-$rClinics->{'ProvID'}\t$rClinics->{'Name'}\n|;
        $sClient->execute( $rClinics->{'ProvID'} );
        while ( my $rClient = $sClient->fetchrow_hashref ) {
            print
              qq|    Client: ${dbname}-$rClient->{'ClientID'}\tLName, FName\n|;
        }
    }
    $sAgency->finish();
    $sClinics->finish();
    $sClient->finish();
    myDBI->cleanup();
}
exit;
#############################################################################
