#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use DBForm;
use DBA;
use DBUtil;
use Time::Local;
$DT = localtime();
############################################################################
# usage:
#   ClientNotEligible ForProvID=id
############################################################################
my $form = DBForm->new;
my $dbh = $form->dbconnect;

my $ForProvID = $form->{ForProvID} ? $form->{ForProvID} : $form->{LOGINPROVID};
my $multidel = chr(253);
############################################################################
my $qInsurance = qq|
select * 
  from Insurance 
    left join xInsurance on xInsurance.ID=Insurance.InsID
  where ClientID=? and Priority=?
    and Insurance.InsNumEffDate<=curdate()
    and (curdate()<=Insurance.InsNumExpDate or Insurance.InsNumExpDate is null)
|;
my $sInsurance = $dbh->prepare($qInsurance);
$sProvider = $dbh->prepare("select * from Provider where ProvID=?");
my $ClinicSelection = DBA->getClinicSelection($form,$ForProvID,'Client.clinicClinicID','where');
$ClinicSelection .= qq| and Client.Active=1| if ( $form->{Active} );
$qClient = qq|select Provider.Name as Clinic
     ,Client.LName, Client.FName, Client.ClientID, Client.Active
     ,Client.DOB, Client.Gend, xRaces.Descr as Race
     ,truncate((to_days(curdate()) - to_days(Client.DOB)) / 365,0) as Age
     ,Client.Zip
     ,ClientReferrals.RefDate
     ,ClientReferrals.ReferredBy1NPI
     ,to_days(curdate()) - to_days(ClientReferrals.RefDate) as Days
     ,xCustAgency.Descr as CustAgency
     ,Client.clinicClinicID
     ,Provider.LName as ProvLName, Provider.FName as ProvFName, Client.ProvID, Provider.Active as PActive
     ,xNPI.ProvOrgName
  from Client
    left join ClientIntake on ClientIntake.ClientID=Client.ClientID
    left join ClientReferrals on ClientReferrals.ClientID=Client.ClientID
    left join ClientLegal on ClientLegal.ClientID=Client.ClientID
    left join Provider on Provider.ProvID=Client.ProvID
    left join okmis_config.xCustAgency on xCustAgency.ID=ClientLegal.CustAgency
    left join okmis_config.xRaces on xRaces.ID=SUBSTRING_INDEX(Client.Race,'${multidel}',1)
    left join okmis_config.xNPI on xNPI.NPI=ClientReferrals.ReferredBy1NPI
  ${ClinicSelection}
  order by Provider.LName, Provider.FName, Client.LName, Client.FName
|;
#warn qq|q=\n$qClient\n| if ( $form->{LOGINPROVID} == 91 );
############################################################################
print qq|${DT}\nClient Eligible Dropped or Not Primary Report\n|;
print qq|Provider\tActive\tClient\tClientID\tActive\tDOB\tGend\tRace\tAge\tZip\tRefDate\tDays\tCustAgency\tPrimary\tStatus\tInsCode\tPlanDescr\tClinic\tReferred By\n|;
my $sClient = $dbh->prepare($qClient);
$sClient->execute() || $form->dberror($query);
while ( my $rClient = $sClient->fetchrow_hashref )
{

  my ($flag,$StatusReason,$PriInsCode) = (0,'','');
  $sInsurance->execute($rClient->{ClientID},1);
  my $rInsurance = $sInsurance->fetchrow_hashref;
  $PriInsCode = $rInsurance->{InsCode};
  my $plan = $PriInsCode eq 'MB' ? " and PlanDescr='Medicare Part B'"
           : $PriInsCode eq 'MC' ? " and (PlanDescr='Title 19' or PlanDescr='Mental Health and Substance Abuse') and Benefit IN ('0','1')"
           : '';
  my $qEligible = qq|select * from Eligible where ClientID=? ${plan} order by FromDate desc, ToDate desc|;
#warn qq|ClientID=$rClient->{ClientID},InsCode=$rInsurance->{InsCode},Descr=$rInsurance->{Descr}\n| if ( $form->{LOGINPROVID} == 91 );
#warn qq|qEligible=$qEligible\n| if ( $form->{LOGINPROVID} == 91 );
  $sEligible = $dbh->prepare($qEligible);
  $sEligible->execute($rClient->{ClientID});
  if ( $rEligible = $sEligible->fetchrow_hashref )
  {

#warn qq|ToDate=$rEligible->{ToDate},Benefit=$rEligible->{Benefit}\n| if ( $form->{LOGINPROVID} == 91 );
#warn qq|InsCode=$rEligible->{InsCode},Benefit=$rEligible->{Benefit}\n| if ( $form->{LOGINPROVID} == 91 );
# if expired by date or code and this elgibility is their primary insurance?
    if ( $rEligible->{ToDate} ne '' && ($rEligible->{ToDate} lt $form->{TODAY} || $rEligible->{Benefit} == 0 ) 
       && $rEligible->{InsCode} eq $rInsurance->{InsCode} )
    { $flag=1; $StatusReason = 'Eligibility Expired'; }
# if they have medicaid/medicare and elgibility is not their primary insurance?
    if ( ($rInsurance->{Descr} eq 'medicaid' || $rInsurance->{Descr} eq 'medicare' ) 
       && $rInsurance->{InsCode} ne $rEligible->{InsCode} )
    { $flag=1; $StatusReason = 'Eligibility Not Primary'; }
  }
#warn qq|flag=$flag,StatusReason=$StatusReason\n| if ( $form->{LOGINPROVID} == 91 );
  if ( $flag )
  {
    print qq|$rClient->{ProvLName}, $rClient->{ProvFName} ($rClient->{ProvID})|;
    print qq|\t$rClient->{PActive}|;
    print qq|\t$rClient->{LName}, $rClient->{FName}\t$rClient->{ClientID}|;
    print qq|\t$rClient->{Active}\t$rClient->{DOB}|;
    print qq|\t$rClient->{Gend}\t$rClient->{Race}\t$rClient->{Age}\t$rClient->{Zip}|;
    print qq|\t$rClient->{RefDate}\t$rClient->{Days}\t$rClient->{CustAgency}|;
    print qq|\t${PriInsCode}\t${StatusReason}\t$rEligible->{InsCode}\t$rEligible->{PlanDescr}|;
    print qq|\t$rClient->{Clinic}\t$rClient->{ProvOrgName}|;
    print qq|\n|;
  }
}
$sInsurance->finish();
$sProvider->finish();
$sEligible->finish();
$sClient->finish();
$form->complete();
exit;
############################################################################
