#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBForm;
use SysAccess;
use DBUtil;
#################################################################
my $form = DBForm->new();
my $dbh = $form->dbconnect();
my $sProvider = $dbh->prepare("select Provider.FName,Provider.LName,ProviderControl.NPI from Provider left join ProviderControl on ProviderControl.ProvID=Provider.ProvID where Provider.ProvID=?");
my $sCredentials = $dbh->prepare("select * from Credentials where ProvID=? and InsID=? order by Rank");
#################################################################
print qq|Descr\tName\tPIN\tNPI\tTaxID\tTaxonomy\tZip\tUseAgency\tProvID\n|;
my $sContracts = $dbh->prepare("select Contracts.InsID,Contracts.PIN,ProviderControl.NPI,Contracts.TaxID,Contracts.Taxonomy,Provider.Name,Provider.ProvID,xInsurance.Descr,Provider.Zip,Contracts.UseAgency from Contracts left join Provider on Provider.ProvID=Contracts.ProvID left join ProviderControl on ProviderControl.ProvID=Contracts.ProvID left join xInsurance on xInsurance.ID=Contracts.InsID where xInsurance.Descr='medicaid'");
$sContracts->execute();
while ( my $rContracts = $sContracts->fetchrow_hashref )
{
  my $cnt=0;
  print qq|$rContracts->{Descr}\t$rContracts->{Name}\t$rContracts->{PIN}\t$rContracts->{NPI}\t$rContracts->{TaxID}\t$rContracts->{Taxonomy}\t$rContracts->{Zip}\t$rContracts->{UseAgency}\t$rContracts->{ProvID}\n|;
  foreach $p ( DBA->getAgencyProvs($form,$rContracts->{ProvID}) )
  {
    $cnt++;
    $sProvider->execute($p);
    my $rProvider = $sProvider->fetchrow_hashref;
    $sCredentials->execute($p,$rContracts->{InsID});
    my $rCredentials = $sCredentials->fetchrow_hashref;
    print qq|provider ${cnt}\t$rProvider->{FName} $rProvider->{LName}\t$rCredentials->{PIN}\t$rProvider->{NPI}\t$rCredentials->{TaxID}\t$rCredentials->{Taxonomy}\n|;
  }
}
$sContracts->finish();
$sCredentials->finish();
$sProvider->finish();
exit;
#################################################################
