#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use myForm;
use myDBI;
use DBA;
use DBUtil;
use Time::Local;
my $DT = localtime();
############################################################################
# usage:
#   MIPS 
############################################################################
my $form = myForm->new();
my $dbh = myDBI->dbconnect($form->{'DBNAME'});
my $debug = $form->{'LOGINPROVID'} == 91 ? 0 : 0;
if ( $debug ) { foreach my $f ( sort keys %{$form} ) { print "form-$f=$form->{$f}\n"; } }
my $Type = $form->{'Type'};
$form->{'FromDate'} = '2019-01-01';
$form->{'ToDate'} = '2019-12-31';
$form = DBUtil->setDates($form);
my $DateRange = qq|from $form->{FromDateD} thru $form->{ToDateD}|;

my $multidel = chr(253);
my $ForProvID = $form->{ForProvID} ? $form->{ForProvID} : $form->{LOGINPROVID};
# join xInsurance needed for withSelection
my $withSelection = DBA->withSelection($form,'and','Client.clinicClinicID','Treatment.ProvID','Treatment.ClientID','Treatment.TrID');
my $Header = DBA->withSelectionHeader($form);
#warn qq|Header: ${Header}\n|;
$withSelection .= qq| and Client.Active=1| if ( $form->{Active} );
  $QID = qq|QID283|;
  $TITLE = qq|Dementia Associated Behavioral and Psychiatric Symptoms Screening and Management - National Quality Strategy Domain: Effective Clinical Care - Meaningful Measure Area: Prevention, Treatment, and Management of Mental Health|;
  $CTYPE = qq|MIPS CLINICAL QUALITY MEASURES (CQMS)|;
  $MTYPE = qq|Process|;
  $DESC = qq|Percentage of patients with dementia for whom there was a documented screening for behavioral and psychiatric symptoms, including depression, and for whom, if symptoms screening was positive, there was also documentation of recommendations for management in the last 12 months|;
  $INST = qq|This measure is to be submitted a minimum of once per performance period for patients with a diagnosis of dementia seen during the performance period. This measure may be submitted by Merit-based Incentive Payment System (MIPS) eligible clinicians who perform the quality actions described in the measure based on the services provided and the measure-specific denominator coding.|;
  my @FLDS = ('ClinicName:ClinicName','LName:LastName','FName:FirstName','ClientID:ClientID','DOB:DateOfBirth','Age:Age','Race:Race','pcount:ProbAddr','PrimaryProvider:PrimaryProvider');
  my $numFLDS = scalar(@FLDS)-3;
print qq|numFLDS=${numFLDS}\n| if ( $debug );
  my $qrecord = qq|
select Treatment.TrID,Treatment.ContLogDate,Treatment.ClinicID,xSC.SCNum
      ,Client.LName,Client.FName,Client.ClientID
      ,Clinic.Name as ClinicName
      ,CONCAT(Counselor.LName,', ',Counselor.FName) as PrimaryProvider
      ,Client.DOB,TIMESTAMPDIFF(YEAR, Client.DOB, CURDATE()) AS Age
      ,xRaces.Descr as Race
      ,misICD10.ICD10
      ,count(*) as pcount
 from Treatment 
  left join Client on Client.ClientID=Treatment.ClientID
  left join Provider as Clinic on Clinic.ProvID=Client.clinicClinicID
  left join Provider as Counselor on Counselor.ProvID=Client.ProvID
  left join okmis_config.xRaces on xRaces.ID=SUBSTRING_INDEX(Client.Race,'${multidel}',1)
  left join xSC on xSC.SCID=Treatment.SCID
  left join xInsurance on xInsurance.ID=xSC.InsID
  left join ClientNoteProblems on ClientNoteProblems.TrID=Treatment.TrID
  left join okmis_config.misICD10 on misICD10.ID=ClientNoteProblems.UUID
 where Client.ClientID>100
   and (Treatment.ContLogDate >= '$form->{FromDate}' and Treatment.ContLogDate<='$form->{ToDate}')
   and (TIMESTAMPDIFF(YEAR, Client.DOB, Treatment.ContLogDate) >= 18)
   and (xSC.SCNum='90791'
        or xSC.SCNum='90792'
        or xSC.SCNum='90832'
        or xSC.SCNum='90834'
        or xSC.SCNum='90837'
        or xSC.SCNum='96150'
        or xSC.SCNum='96151'
        or xSC.SCNum='96152'
        or xSC.SCNum='97161'
        or xSC.SCNum='97162'
        or xSC.SCNum='97163'
        or xSC.SCNum='97165'
        or xSC.SCNum='97166'
        or xSC.SCNum='97167'
        or xSC.SCNum='97802'
        or xSC.SCNum='97803'
        or xSC.SCNum='99201'
        or xSC.SCNum='99202'
        or xSC.SCNum='99203'
        or xSC.SCNum='99204'
        or xSC.SCNum='99205'
        or xSC.SCNum='99212'
        or xSC.SCNum='99213'
        or xSC.SCNum='99214'
        or xSC.SCNum='99215'
        or xSC.SCNum='99236'
        or xSC.SCNum='99304'
        or xSC.SCNum='99305'
        or xSC.SCNum='99306'
        or xSC.SCNum='99307'
        or xSC.SCNum='99308'
        or xSC.SCNum='99309'
        or xSC.SCNum='99310'
        or xSC.SCNum='99315'
        or xSC.SCNum='99316'
        or xSC.SCNum='99318'
        or xSC.SCNum='99324'
        or xSC.SCNum='99325'
        or xSC.SCNum='99326'
        or xSC.SCNum='99327'
        or xSC.SCNum='99328'
        or xSC.SCNum='99334'
        or xSC.SCNum='99335'
        or xSC.SCNum='99336'
        or xSC.SCNum='99337'
        or xSC.SCNum='99339'
        or xSC.SCNum='99340'
        or xSC.SCNum LIKE '99385%'
        or xSC.SCNum LIKE '99386%'
        or xSC.SCNum LIKE '99387%'
        or xSC.SCNum LIKE '99395%'
        or xSC.SCNum LIKE '99396%'
        or xSC.SCNum LIKE '99397%'
        or xSC.SCNum='99401'
        or xSC.SCNum='99402'
        or xSC.SCNum='D7140'
        or xSC.SCNum='D7210'
        or xSC.SCNum='G0101'
        or xSC.SCNum='G0108'
        or xSC.SCNum='G0270'
        or xSC.SCNum='G0271'
        or xSC.SCNum='G0402'
        or xSC.SCNum='G0438'
        or xSC.SCNum='G0439'
        or xSC.SCNum='G0447'
        or xSC.SCNum='G0473'
       )
  ${withSelection}
 group by Client.LName,Client.FName,Client.ClientID
|;
# group by Client.LName,Client.FName,Client.ClientID,xSC.SCNum,misICD10.ICD10
#warn qq|qrecord=\n${qrecord}\n|;
my ($Denominator,$Numerator,$total) = (0,0,0);
print qq|${DT}\n${QID} ${TITLE} ${DateRange} ${Header}\n|;
foreach my $f ( @FLDS ) { my ($fld,$hdr) = split(':',$f); print qq|${hdr}\t|; }
print qq|\n|;
my $sGCodeExclude = $dbh->prepare("select TrID 
 from Treatment left join xSC on xSC.SCID=Treatment.SCID 
 where Treatment.ClientID=? 
   and (Treatment.ContLogDate >= '$form->{FromDate}' and Treatment.ContLogDate<='$form->{ToDate}')
   and xSC.SCNum IN ('G8422','G8938')");
my $sGCode = $dbh->prepare("select TrID 
 from Treatment left join xSC on xSC.SCID=Treatment.SCID 
 where Treatment.ClientID=? 
   and (Treatment.ContLogDate >= '$form->{FromDate}' and Treatment.ContLogDate<='$form->{ToDate}')
   and xSC.SCNum IN ('G8417','G8418','G8419','G8420','G8421')");
my $srecord = $dbh->prepare($qrecord);
$srecord->execute();
while (my $rrecord = $srecord->fetchrow_hashref)
{ 
# DENOMINATOR EXCLUSIONS:
# BMI not documented, documentation the patient is not eligible for BMI calculation: G8422
# OR
# BMI is documented as being outside of normal limits, follow-up plan is not documented,
# documentation the patient is not eligible: G8938
  $sGCodeExclude->execute($rrecord->{'ClientID'});
  my $rGCodeExclude = $sGCodeExclude->fetchrow_hashref;
  my $cnt = $sGCodeExclude->rows;
#print qq|\nFOUND: $rrecord->{'ClientID'}, count=${cnt}\n|;
  next if ( $cnt );             # must NOT have G8422 or G8938.
#print qq|PASSED: $rrecord->{'ClientID'}, count=$rGCodeExclude->{'count'}/$rGCode2->{'count'}\n|;

  $Denominator++;
  $sGCode->execute($rrecord->{'ClientID'});
  if (my $rGCode = $sGCode->fetchrow_hashref)
  { $Numerator++; }
  foreach my $f ( @FLDS ) { my ($fld,$hdr) = split(':',$f); print qq|$rrecord->{$fld}\t|; }
  print qq|\n|;
  $total += $rrecord->{'pcount'};
}
print qq|Numerator\t${Numerator}|."\t" x $numFLDS.qq|${total}\n|;
print qq|Denominator\t${Denominator}\n|;
$srecord->finish();
$sGCode->finish();
$sGCodeExclude->finish();

myDBI->cleanup();
exit;
############################################################################
# where (Client.ClientID=50234 or Client.ClientID=60348 or Client.ClientID=46424 or Client.ClientID=56680 or Client.ClientID=49679)
