#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use myForm;
use myDBI;
use DBA;
use DBUtil;
use Time::Local;
my $DT = localtime();
############################################################################
# usage:
#   MIPS 
############################################################################
my $form = myForm->new();
my $dbh = myDBI->dbconnect($form->{'DBNAME'});
my $debug = $form->{'LOGINPROVID'} == 91 ? 0 : 0;
if ( $debug ) { foreach my $f ( sort keys %{$form} ) { print "form-$f=$form->{$f}\n"; } }
my $Type = $form->{'Type'};
$form->{'FromDate'} = '2019-01-01';
$form->{'ToDate'} = '2019-12-31';
$form = DBUtil->setDates($form);
my $DateRange = qq|from $form->{FromDateD} thru $form->{ToDateD}|;

my $multidel = chr(253);
my $ForProvID = $form->{ForProvID} ? $form->{ForProvID} : $form->{LOGINPROVID};
# join xInsurance needed for withSelection
my $withSelection = DBA->withSelection($form,'and','Treatment.ClinicID','Treatment.ProvID','Treatment.ClientID','Treatment.TrID');
my $Header = DBA->withSelectionHeader($form);
#warn qq|Header: ${Header}\n|;
$withSelection .= qq| and Client.Active=1| if ( $form->{Active} );
  $QID = qq|QID402|;
  $TITLE = qq|Tobacco Use and Help with Quitting Among Adolescents - National Quality Strategy Domain: Community/Population Health - Meaningful Measure Area: Prevention and Treatment of Opioid and Substance Use Disorders|;
  $CTYPE = qq|MIPS CLINICAL QUALITY MEASURES (CQMS)|;
  $MTYPE = qq|Process|;
  $DESC = qq|The percentage of adolescents 12 to 20 years of age with a primary care visit during the measurement year for whom tobacco use status was documented and received help with quitting if identified as a tobacco user|;
  $INST = qq|This measure is to be submitted once per performance period for patients seen during the performance period. This measure is intended to reflect the quality of services provided for preventive screening for tobacco use. This measure may be submitted by Merit-based Incentive Payment System (MIPS) eligible clinicians who perform the quality actions described in the measure based on the services provided and the measure-specific denominator coding.|;
  my @FLDS = ('ClinicName:ClinicName','LName:LastName','FName:FirstName','ClientID:ClientID','DOB:DateOfBirth','Age:Age','Race:Race','pcount:ProbAddr','PrimaryProvider:PrimaryProvider');
  my $numFLDS = scalar(@FLDS)-3;
print qq|numFLDS=${numFLDS}\n| if ( $debug );
  my $qrecord = qq|
select Treatment.TrID,Treatment.ContLogDate,Treatment.ClinicID,xSC.SCNum
      ,Client.LName,Client.FName,Client.ClientID
      ,Clinic.Name as ClinicName
      ,CONCAT(Counselor.LName,', ',Counselor.FName) as PrimaryProvider
      ,Client.DOB,TIMESTAMPDIFF(YEAR, Client.DOB, CURDATE()) AS Age
      ,xRaces.Descr as Race
      ,misICD10.ICD10
      ,count(*) as pcount
 from Treatment 
  left join Client on Client.ClientID=Treatment.ClientID
  left join Provider as Clinic on Clinic.ProvID=Client.clinicClinicID
  left join Provider as Counselor on Counselor.ProvID=Client.ProvID
  left join okmis_config.xRaces on xRaces.ID=SUBSTRING_INDEX(Client.Race,'${multidel}',1)
  left join xSC on xSC.SCID=Treatment.SCID
  left join xInsurance on xInsurance.ID=xSC.InsID
  left join ClientNoteProblems on ClientNoteProblems.TrID=Treatment.TrID
  left join okmis_config.misICD10 on misICD10.ID=ClientNoteProblems.UUID
 where Client.ClientID>100
   and (Treatment.ContLogDate >= '$form->{FromDate}' and Treatment.ContLogDate<='$form->{ToDate}')
   and (
         (TIMESTAMPDIFF(YEAR, Client.DOB, Treatment.ContLogDate) >= 12)
         and (TIMESTAMPDIFF(YEAR, Client.DOB, Treatment.ContLogDate) <= 20)
       )
   and (xSC.SCNum='90791'
        or xSC.SCNum='90792'
        or xSC.SCNum='90832'
        or xSC.SCNum='90834'
        or xSC.SCNum='90837'
        or xSC.SCNum='90839'
        or xSC.SCNum='90845'
        or xSC.SCNum='92002'
        or xSC.SCNum='92004'
        or xSC.SCNum='92012'
        or xSC.SCNum='92014'
        or xSC.SCNum='96150'
        or xSC.SCNum='96151'
        or xSC.SCNum='96152'
        or xSC.SCNum='97165'
        or xSC.SCNum='97166'
        or xSC.SCNum='97167'
        or xSC.SCNum='97168'
        or xSC.SCNum='99201'
        or xSC.SCNum='99202'
        or xSC.SCNum='99203'
        or xSC.SCNum='99204'
        or xSC.SCNum='99205'
        or xSC.SCNum='99212'
        or xSC.SCNum='99213'
        or xSC.SCNum='99214'
        or xSC.SCNum='99215'
        or xSC.SCNum='99406'
        or xSC.SCNum='99407'
        or xSC.SCNum='G0438'
        or xSC.SCNum='G0439'
       )
  ${withSelection}
 group by Client.LName,Client.FName,Client.ClientID
|;
# group by Client.LName,Client.FName,Client.ClientID,xSC.SCNum,misICD10.ICD10
#warn qq|qrecord=\n${qrecord}\n|;
my ($Numerator,$Denominator,$total) = (0,0,0);
print qq|${DT}\n${QID} ${TITLE} ${DateRange} ${Header}\n|;
foreach my $f ( @FLDS ) { my ($fld,$hdr) = split(':',$f); print qq|${hdr}\t|; }
print qq|\n|;
my $sGCode = $dbh->prepare("select TrID 
 from Treatment left join xSC on xSC.SCID=Treatment.SCID 
 where Treatment.ClientID=? 
   and (Treatment.ContLogDate >= '$form->{FromDate}' and Treatment.ContLogDate<='$form->{ToDate}')
   and xSC.SCNum IN ('G9458','G9459','G9460')");
my $srecord = $dbh->prepare($qrecord);
$srecord->execute();
while (my $rrecord = $srecord->fetchrow_hashref)
{ 
  $Denominator++;
  $sGCode->execute($rrecord->{'ClientID'});
  if (my $rGCode = $sGCode->fetchrow_hashref)
  { $Numerator++; }
  foreach my $f ( @FLDS ) { my ($fld,$hdr) = split(':',$f); print qq|$rrecord->{$fld}\t|; }
  print qq|\n|;
  $total += $rrecord->{'pcount'};
}
print qq|Numerator\t${Numerator}|."\t" x $numFLDS.qq|${total}\n|;
print qq|Denominator\t${Denominator}\n|;
$srecord->finish();
$sGCode->finish();

myDBI->cleanup();
exit;
############################################################################
# where (Client.ClientID=50234 or Client.ClientID=60348 or Client.ClientID=46424 or Client.ClientID=56680 or Client.ClientID=49679)
