#!/usr/bin/perl
use lib '/var/www/okmis/src/lib';

use DBI;
use myForm;
use myDBI;
use DBA;
use DBUtil;
use Time::Local;
my $DT = localtime();
############################################################################
# usage:
#   MIPS
############################################################################
my $form  = myForm->new();
my $dbh   = myDBI->dbconnect( $form->{'DBNAME'} );
my $debug = $form->{'LOGINPROVID'} == 91 ? 0 : 0;
if ($debug) {
    foreach my $f ( sort keys %{$form} ) { print "form-$f=$form->{$f}\n"; }
}
my $Type = $form->{'Type'};
$form = DBUtil->setDates($form);
my $DateRange = qq|from $form->{FromDateD} thru $form->{ToDateD}|;

my $multidel  = 'ý';
my $ForProvID = $form->{ForProvID} ? $form->{ForProvID} : $form->{LOGINPROVID};

# join xInsurance needed for withSelection
my $withSelection = DBA->withSelection( $form, 'and', 'Client.clinicClinicID',
    'Treatment.ProvID', 'Treatment.ClientID', 'Treatment.TrID' );
my $Header = DBA->withSelectionHeader($form);

#warn qq|Header: ${Header}\n|;
$withSelection .= qq| and Client.Active=1| if ( $form->{Active} );
$QID = qq|QID128|;
$TITLE =
qq|Preventive Care and Screening: Body Mass Index (BMI) Screening and Follow-Up Plan - National Quality Strategy Domain: Community/Population Health - Meaningful Measure Area: Preventive Care|;
my $CTYPE = qq|MIPS CLINICAL QUALITY MEASURES (CQMS)|;
my $MTYPE = qq|Process|;
my $DESC =
qq|Percentage of patients aged 18 years and older with a BMI documented during the current encounter or within the previous twelve months AND who had a follow-up plan documented if most recent BMI was outside of normal parameters|;
my $INST =
qq|There is no diagnosis associated with this measure. This measure is to be submitted a minimum of once per
performance period for patients seen during the performance period. This measure may be submitted by Meritbased Incentive Payment System (MIPS) eligible clinicians who perform the quality actions described in the measure 
based on the services provided at the time of the qualifying visit and the measure-specific denominator coding. The 
BMI may be documented in the medical record of the provider or in outside medical records obtained by the provider. 
If the most recent documented BMI is outside of normal parameters, then a follow-up plan is documented during the 
encounter or during the previous twelve months of the current encounter. The documented follow-up plan must be 
based on the most recent documented BMI outside of normal parameters, example: “Patient referred to nutrition 
counseling for BMI above or below normal parameters” (See Definitions for examples of follow-up plan treatments). If 
more than one BMI is submitted during the measurement period, the most recent BMI will be used to determine if the 
performance has been met. Review the exclusions and exceptions criteria to determine those patients that BMI 
measurement may not be appropriate or necessary.|;
my @FLDS = (
    'ClinicName:ClinicName',           'LName:LastName',
    'FName:FirstName',                 'ClientID:ClientID',
    'DOB:DateOfBirth',                 'Age:Age',
    'Race:Race',                       'pcount:ProbAddr',
    'PrimaryProvider:PrimaryProvider', "Insurance:Insurance",
    "BMI:BMI"
);
my $numFLDS = scalar(@FLDS) - 2;
print qq|numFLDS=${numFLDS}\n| if ($debug);

my $ClientSelection =
  DBA->withSelection( $form, 'and', 'Client.clinicClinicID', 'Client.ProvID' );

my ( $Denominator, $total, $PFMET, $DNEXCEPTION, $PFNOTMET, $DNEXCLUDED ) =
  ( 0, 0, 0, 0, 0, 0 );

my $table_header = '';
foreach my $f (@FLDS) {
    my ( $fld, $hdr ) = split( ':', $f );
    $table_header .= qq|${hdr}\t|;
}
$table_header .= qq|\n|;
$table_entries = '';

$form = DBUtil->setDates($form);

my $sClientVitalSigns = $dbh->prepare(
    "select * from ClientVitalSigns where ClientID=? and
    vDate BETWEEN '2024-01-01' AND '2024-12-31' order by VDate"
);

my $qRecord = qq|
    select Treatment . TrID, Treatment . ContLogDate, xSC . SCNum,
      xInsurance . Descr as Insurance,
    Client . LName, Client . FName
    , Clinic . Name as ClinicName
        , Client . ClientID, Provider . ProvID, ClientEmergency . HospiceCheck
        , CONCAT( Provider . LName, ', ', Provider . FName ) as PrimaryProvider
        ,CONCAT(Client.LName,', ',Client.FName) as ClientName
        ,Client.DOB,TIMESTAMPDIFF(YEAR, Client.DOB, CURDATE()) AS Age
        ,count(*) as pcount
    from Treatment 
    left join Client on Client.ClientID=Treatment.ClientID
    LEFT JOIN ClientEmergency ON Client
      . ClientID = ClientEmergency
      . ClientID
    left join Provider on Provider.ProvID=Treatment.ProvID
    left join Provider as Clinic on Clinic . ProvID = Client . clinicClinicID
    left join xSC on xSC.SCID=Treatment.SCID
    left join xInsurance on xInsurance.ID=xSC.InsID
    WHERE Treatment.ContLogDate BETWEEN '2024-01-01' AND '2024-12-31' AND
    TIMESTAMPDIFF( YEAR, Client . DOB, CURDATE() ) >= 18
    AND Treatment
      . ProvID IN( "2118", "2128", "2686", "958" ) AND xInsurance
      . ID = 212
    AND Treatment.ClinicID=101
    AND(
        xSC.SCNum IN(
            '90791', '90792', '90832', '90834', '90837', '96156',
            '96158', '97161', '97162', '97163', '97165', '97166',
            '97167', '97802', '97803', '99202', '99203', '99204',
            '99205', '99212', '99213', '99214', '99215', '99304',
            '99305', '99306', '99307', '99308', '99309', '99310',
            '99315', '99316', '99341', '99342', '99344', '99345',
            '99347', '99348', '99349', '99350', '99424', '99491',
            'D7111', 'D7140', 'D7210', 'D7220', 'D7230', 'D7240',
            'D7241', 'D7250', 'D7251', 'G0101', 'G0108', 'G0270',
            'G0271', 'G0402', 'G0438', 'G0439', 'G0447', 'G0473'
        ) OR xSC
        . SCNum LIKE '99385%' OR xSC
        . SCNum LIKE '99386%' OR xSC
        . SCNum LIKE '99387%' OR xSC
        . SCNum LIKE '99395%' OR xSC
        . SCNum LIKE '99396%' OR xSC
        . SCNum LIKE '99397%' OR xSC
        . SCNum LIKE '99401%' OR xSC
        . SCNum LIKE '99402%'
    )


 group by Treatment.ClientID
|;

my $sCheckHospice = $dbh->prepare(
    "SELECT cp.InitiatedDate, i.ICD10, i.sctName FROM ClientProblems cp
		LEFT JOIN okmis_config.misICD10 i ON cp.UUID = i.ID 
		WHERE cp.ClientID = ? AND
		i.ICD10 = 'Z51.5'"
);

my $sRecord = $dbh->prepare($qRecord);
$sRecord->execute();
while ( my $rRecord = $sRecord->fetchrow_hashref ) {
    $Denominator++;
    my $HospiceCheck = $rRecord->{'HospiceCheck'};

    $rRecord->{"BMI"} = "";
    my $ClientID = $rRecord->{'ClientID'};

    $sCheckHospice->execute($ClientID);

    if ( $sCheckHospice->rows > 0 ) {

        $DNEXCLUDED++;
        $rRecord->{"BMI"} = "Excluded";
    }
    else {
        $sClientVitalSigns->execute($ClientID);
        my $rClientVitalSigns = $sClientVitalSigns->fetchrow_hashref;
        my $BMI               = $rClientVitalSigns->{BMI};
        my $HeightFeet        = $rClientVitalSigns->{HeightFeet};
        my $HeightInches      = $rClientVitalSigns->{HeightInches};
        my $Weight            = $rClientVitalSigns->{Weight};

        if (   $rClientVitalSigns->{ID} eq ""
            || $rClientVitalSigns->{ID} eq "null" )
        {
            $PFNOTMET++;
            $rRecord->{"BMI"} = "No Vitals";
        }
        else {
            if ( $BMI ne "" || ( $HeightFeet && $Weight ) ) {
                $PFMET++;
                if ( $BMI eq "" || $BMI eq "0.00" ) {
                    if ( $HeightFeet > 0 && $Weight > 0 ) {
                        my $height = ( $HeightFeet * 12 ) + $HeightInches;

                        my $bmi = ( $Weight / ( $height * $height ) ) * 703;
                        $bmi = sprintf( "%.2f", $bmi );

                        $rRecord->{"BMI"} = $bmi . " MET";
                    }
                    else {
                        $PFNOTMET++;
                        $rRecord->{"BMI"} = "No BMI";
                    }
                }
                else {
                    $rRecord->{"BMI"} = $BMI . " MET";
                }
            }
            else {
                $PFNOTMET++;
                $rRecord->{"BMI"} = "No BMI";
            }
        }

    }

    foreach my $f (@FLDS) {
        my ( $fld, $hdr ) = split( ':', $f );
        $table_entries .= qq|$rRecord->{$fld}\t|;
    }

    $table_entries .= qq|\n|;

    $total += $rRecord->{'pcount'};
}

my $Data_Completeness_Rate;
my $Performance_Rate;

my $Data_Completeness_Numerator =
  $PFMET + $DNEXCEPTION + $PFNOTMET + $DNEXCLUDED;

if ( $Denominator eq 0 ) {

    $Data_Completeness_Rate = 0;
    $Performance_Rate       = 0;

}
else {

    $Data_Completeness_Rate =
      ( $Data_Completeness_Numerator / $Denominator ) * 100;
    if ( $Data_Completeness_Numerator > ( $DNEXCEPTION + $DNEXCLUDED ) ) {
        $Performance_Rate =
          ( $PFMET /
              ( $Data_Completeness_Numerator - $DNEXCLUDED - $DNEXCEPTION ) ) *
          100;
    }
}

$Data_Completeness_Rate = sprintf( "%.2f", $Data_Completeness_Rate );
$Performance_Rate       = sprintf( "%.2f", $Performance_Rate );

my $nom_denom =
qq|Numerator = Denominator Exclusion (${DNEXCLUDED}) + Performance Met (${PFMET}) +  Denominator Exception (${DNEXCEPTION}) +  Performance Not Met (${PFNOTMET})= ${Data_Completeness_Numerator} \n Denominator(Eligible Population) = ${Denominator}\n|;
my $Data_Completeness_Rate_Text =
qq|Data Completeness Rate = Numerator(${Data_Completeness_Numerator}) / Denominator(${Denominator}) = ${Data_Completeness_Rate}% \n|;
my $Performance_Rate_Text =
qq|Performance Rate = Performance Met (${PFMET}) / Numerator(${Data_Completeness_Numerator}) - Denominator Exclusion (${DNEXCLUDED}) - Denominator Exception (${DNEXCEPTION}) = ${Performance_Rate}% \n|;

$Header = qq|${DT}\n${QID} ${TITLE} ${DateRange} ${Header} \n ${nom_denom}|;

print $Header;
print $Data_Completeness_Rate_Text;
print $Performance_Rate_Text;
print $table_header;
print $table_entries;

print qq|${Denominator}| . "\t" x $numFLDS . qq|${total}\n|;

$sClientVitalSigns->finish();
$sRecord->finish();
myDBI->cleanup();
exit;
############################################################################
# where (Client.ClientID=50234 or Client.ClientID=60348 or Client.ClientID=46424 or Client.ClientID=56680 or Client.ClientID=49679)
