#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use Accounts;
use myConfig;
use myDBI;
use Cwd;
############################################################################
# usage: command [id|list]                   for all accounts
#    or: command [id|list] acct1 acct2...    to run for 'acct1' 'acct2' ...
############################################################################
#print "@ARGV\n";
# get the command name...
my ($pw,$cmd) = $0 =~ m/(.*\/)(.*)$/;
my $ID = shift;
# the databases to work with
my @DBS = $ARGV[0] eq 'test' ? Accounts->dbs('test') : scalar(@ARGV) ? @ARGV : Accounts->dbs('active'); 
# avoid the GenReports.cgi sending the DBNAME= on command line.
@DBS = Accounts->dbs('active') if ( $ARGV[0] =~ /DBNAME=/ );
#print "@DBS\n";

############################################################################
my $dbh = myDBI->dbconnect('okmis_config');
my $sEmail = $dbh->prepare("select * from MISEmails where ID='${ID}'");
$sEmail->execute();
my $rEmail = $sEmail->fetchrow_hashref;
$sEmail->finish();
myDBI->cleanup();
if ( $ID =~ /list/i )
{ main->List(); }
elsif ( $rEmail->{MSG} eq '' )
{ print qq|NO EMAIL FOUND! (ID=${ID})\n|; }
else
{ main->Send($rEmail->{'SUBJ'},$rEmail->{'MSG'}); }
exit;

############################################################################
sub List
{
  my ($self) = @_;
  print qq|DB\tLastName\tFirstName\tProvID\tEmail\n|;
  foreach my $dbname ( @DBS )
  {
    my $pwd=cwd();
    my $dbh = myDBI->dbconnect($dbname);
    my $sProvider = $dbh->prepare("select Provider.LName,Provider.FName,Provider.Email from Provider left join ProviderPrefs on ProviderPrefs.ProvID=Provider.ProvID where Provider.Active=1 and ProviderPrefs.MISEmails=1 order by Provider.LName,Provider.FName");
    $sProvider->execute();
    while ( my $rProvider = $sProvider->fetchrow_hashref )
    { print qq|${dbname}\t$rProvider->{LName}\t$rProvider->{'FName'}\t$rProvider->{'ProvID'}\t$rProvider->{'Email'}\n|; }
    $sProvider->finish();
    myDBI->cleanup();
  }
  return(1);
}
sub Send
{
  my ($self,$SUBJ,$MSG) = @_;
  print qq|${cmd} Started: |.localtime().qq|\n\n|;
  print qq|======================================\n\n|;

  foreach my $dbname ( @DBS )
  {
    my $pwd=cwd();
    print qq|\n--------------------------------------\n|;
    print qq|database: ${dbname} \n|;
    my $dbh = myDBI->dbconnect($dbname);
    my $sProvider = $dbh->prepare("select Provider.LName,Provider.FName,Provider.Email from Provider left join ProviderPrefs on ProviderPrefs.ProvID=Provider.ProvID where Provider.Active=1 and ProviderPrefs.MISEmails=1 order by Provider.LName,Provider.FName");
    $sProvider->execute();
    while ( my $rProvider = $sProvider->fetchrow_hashref )
    {
      print qq|To: $rProvider->{LName}, $rProvider->{'FName'}, $rProvider->{'Email'} \n|;
      DBUtil->email($form,$rProvider->{'Email'},$SUBJ,$MSG,'',1);
    }
    $sProvider->finish();
    myDBI->cleanup();
  }
  print qq|\n--------------------------------------\n|;
  print qq|To: Autumn autumna@okmis.com\n|;
  DBUtil->email($form,'autumn@okmis.com',$SUBJ,$MSG,'',1);
  print qq|To: Darrell darrell@okmis.com\n|;
  DBUtil->email($form,'darrell@okmis.com',$SUBJ,$MSG,'',1);
  print qq|To: support support@okmis.com\n|;
  DBUtil->email($form,'support@okmis.com',$SUBJ,$MSG,'',1);

  print qq|\n\n======================================\n|;
  print qq|${cmd} Completed: |.localtime().qq|\n|;
  return(1);
}
############################################################################
