#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use Cwd;
use DBI;
use DBForm;
use DBUtil;
use myConfig;
use myHTML;
use SysAccess;
use gXML;
use XML::LibXSLT;
use XML::LibXML;
binmode STDOUT, ":utf8";
my $debug = 1;

############################################################################
my $form = DBForm->new();
my $dbh = $form->dbconnect();
$form->{'FromDate'} = '2017-11-01';
$form->{'ToDate'} = '2017-11-31';

warn qq|\n\ngenQRDAs: ENTER\n| if ( $debug );
if ( $debug ) { foreach my $f ( sort keys %{$form} ) { warn "genQRDAs: form-$f=$form->{$f}<BR>\n"; } }
  my $Token = DBUtil->genToken();
$Token = 'kls';
  my $Folder = $form->{'Folder'} ? $form->{'Folder'} : $Token;
  my $ForProvID = $form->{'ForProvID'} ? $form->{'ForProvID'} : $form->{'LOGINPROVID'};
  $form = DBUtil->setDates($form);
  $form->{'ProvIDs'} = $form->{'ForProvID'} if ( $form->{'ProvIDs'} eq '' );
  $form->{'MEASUREID'} = $form->{'CQM'};
  my $cnt = 0;
warn qq|genQRDAs: foreach: ClientIDs=$form->{ClientIDs}=\n| if ( $debug );
  foreach my $ProvID ( split(chr(253),$form->{ProvIDs}) )
  {
    foreach my $ClientID ( split(chr(253),$form->{ClientIDs}) )
    {
warn qq|genQRDAs: setXML: ClientID=${ClientID}=\n| if ( $debug );
      my $xml = qq|<?xml version="1.0" encoding="utf-8"?>\n|.gXML->setXML($form,$ProvID,$ClientID,'',$form->{FromDate},$form->{ToDate},'QRDA nonulls');
      my $xmlfile = qq|/tmp/XML_${Token}_${ProvID}_${ClientID}_$form->{'MEASUREID'}.xml|;
      my $xmlpath = qq|$form->{DOCROOT}${xmlfile}|;
      open(XML, ">", $xmlpath) || die "Couldn't open '${xmlpath}' file: $!"; 
      print XML $xml;
      close(XML);

      # next the generate QRDA file...
      my $visitout = gXML->styleQRDA($form,$xmlfile);
      my $visitfile = qq|/tmp/QRDA_${Token}_${ProvID}_${ClientID}_$form->{'MEASUREID'}.xml|;
      my $visitpath = qq|$form->{DOCROOT}${visitfile}|;
      open(OUT, ">:encoding(UTF-8)", $visitpath) || die "Couldn't open '${visitpath}' file: $!"; 
      print OUT $visitout;
      close(OUT);
      $cnt++;
    }
  }

  my $result = '';
  if ( $cnt )  ## create temporary directory for files created and zip from this shell...
  {
    my $BIN = myConfig->cfg('BIN');
    my $shell = `${BIN}/zipFILEs $form->{'DOCROOT'} "QRDA_${Token}* XML_${Token}*" ${Folder} ${ForProvID}`;
warn qq|shell=${shell}\n| if ( $debug );
  }
  else { warn qq|\nCount is zero selected! - No files created!\n|; }
############################################################################
