CREATE TABLE `ClientCSSRS` (
  `ID` int(11) NOT NULL,
  `ClientID` int(11) DEFAULT NULL,
  `CreateProvID` int(11) DEFAULT NULL,
  `CreateDate` date DEFAULT NULL,
  `ChangeProvID` int(11) DEFAULT NULL,
  `ChangeDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FormID` varchar(12) DEFAULT NULL,
  `Locked` char(1) DEFAULT NULL,
  `TestDate` date DEFAULT NULL,
  `q1` char(1) DEFAULT NULL,
  `q2` text,
  `q3` char(1) DEFAULT NULL,
  `q4` text,
  `q5` char(1) DEFAULT NULL,
  `q6` text,
  `q7` char(1) DEFAULT NULL,
  `q8` text,
  `q9` char(1) DEFAULT NULL,
  `q10` text,
  `q11` int(11) DEFAULT NULL,
  `q12` text,
  `q13` int(11) DEFAULT NULL,
  `q14` int(11) DEFAULT NULL,
  `q15` int(11) DEFAULT NULL,
  `q16` int(11) DEFAULT NULL,
  `q17` int(11) DEFAULT NULL,
  `q18` char(1) DEFAULT NULL,
  `q19` varchar(11) DEFAULT NULL,
  `q20` varchar(11) DEFAULT NULL,
  `q21` varchar(11) DEFAULT NULL,
  `q22` varchar(11) DEFAULT NULL,
  `q23` date DEFAULT NULL,
  `q24` int(11) DEFAULT NULL,
  `q25` int(11) DEFAULT NULL,
  `q1h` char(1) DEFAULT NULL,
  `q2h` text,
  `q3h` char(1) DEFAULT NULL,
  `q4h` text,
  `q5h` char(1) DEFAULT NULL,
  `q6h` text,
  `q7h` char(1) DEFAULT NULL,
  `q8h` text,
  `q9h` char(1) DEFAULT NULL,
  `q10h` text,
  `q11h` int(11) DEFAULT NULL,
  `q12h` text,
  `q13h` int(11) DEFAULT NULL,
  `q14h` int(11) DEFAULT NULL,
  `q15h` int(11) DEFAULT NULL,
  `q16h` int(11) DEFAULT NULL,
  `q17h` int(11) DEFAULT NULL,
  `q18h` char(1) DEFAULT NULL,
  `q19h` varchar(11) DEFAULT NULL,
  `q20h` varchar(11) DEFAULT NULL,
  `q21h` varchar(11) DEFAULT NULL,
  `q22h` varchar(11) DEFAULT NULL,
  `q23h` date DEFAULT NULL,
  `q24h` int(11) DEFAULT NULL,
  `q25h` int(11) DEFAULT NULL,
  `q26` char(1) DEFAULT NULL,
  `q26h` char(1) DEFAULT NULL,
  `q27` text,
  `q28` char(1) DEFAULT NULL,
  `q28h` char(1) DEFAULT NULL,
  `q29` text,
  `q30` char(1) DEFAULT NULL,
  `q30h` char(1) DEFAULT NULL,
  `q31` text,
  `q32` date DEFAULT NULL,
  `q33` text,
  `q34` varchar(11) DEFAULT NULL,
  `q35` char(1) DEFAULT NULL,
  `q35h` char(1) DEFAULT NULL,
  `q36` char(1) DEFAULT NULL,
  `q36h` char(1) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `ClientCSSRS`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `ClientCSSRS`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

