CREATE TABLE `ClientCSSRSt` (
  `ID` int(11) NOT NULL,
  `ClientID` int(11) DEFAULT NULL,
  `CreateProvID` int(11) DEFAULT NULL,
  `CreateDate` date DEFAULT NULL,
  `ChangeProvID` int(11) DEFAULT NULL,
  `ChangeDate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FormID` varchar(12) DEFAULT NULL,
  `Locked` char(1) DEFAULT NULL,
  `TestDate` date DEFAULT NULL,
  `q1` char(1) DEFAULT NULL,
  `q2` char(1) DEFAULT NULL,
  `q3` char(1) DEFAULT NULL,
  `q4` char(1) DEFAULT NULL,
  `q5` char(1) DEFAULT NULL,
  `q6` char(1) DEFAULT NULL,
  `q7` char(1) DEFAULT NULL,
  `q8` char(1) DEFAULT NULL,
  `q9` char(1) DEFAULT NULL,
  `q10` char(1) DEFAULT NULL,
  `q11` char(1) DEFAULT NULL,
  `q12` char(1) DEFAULT NULL,
  `q13` char(1) DEFAULT NULL,
  `q14` char(1) DEFAULT NULL,
  `q15` char(1) DEFAULT NULL,
  `q16` text,
  `q17` text,
  `q18` text,
  `q19` char(1) DEFAULT NULL,
  `q20` char(1) DEFAULT NULL,
  `q21` char(1) DEFAULT NULL,
  `q22` char(1) DEFAULT NULL,
  `q23` char(1) DEFAULT NULL,
  `q24` char(1) DEFAULT NULL,
  `q25` char(1) DEFAULT NULL,
  `q26` char(1) DEFAULT NULL,
  `q27` char(1) DEFAULT NULL,
  `q28` char(1) DEFAULT NULL,
  `q29` char(1) DEFAULT NULL,
  `q30` char(1) DEFAULT NULL,
  `q31` char(1) DEFAULT NULL,
  `q32` char(1) DEFAULT NULL,
  `q33` char(1) DEFAULT NULL,
  `q34` char(1) DEFAULT NULL,
  `q35` char(1) DEFAULT NULL,
  `q36` text,
  `q37` text,
  `q38` char(1) DEFAULT NULL,
  `q39` char(1) DEFAULT NULL,
  `q40` char(1) DEFAULT NULL,
  `q41` char(1) DEFAULT NULL,
  `q42` text,
  `q43` text,
  `q44` text,
  `q45` text,
  `q46` text,
  `q47` char(1) DEFAULT NULL,
  `q48` char(1) DEFAULT NULL,
  `q49` char(1) DEFAULT NULL,
  `q50` char(1) DEFAULT NULL,
  `q51` char(1) DEFAULT NULL,
  `q52` char(1) DEFAULT NULL,
  `q53` char(1) DEFAULT NULL,
  `q54` char(1) DEFAULT NULL,
  `q55` char(1) DEFAULT NULL,
  `q56` char(1) DEFAULT NULL,
  `q57` char(1) DEFAULT NULL,
  `q58` char(1) DEFAULT NULL,
  `q59` char(1) DEFAULT NULL,
  `q60` char(1) DEFAULT NULL,
  `q61` char(1) DEFAULT NULL,
  `q62` char(1) DEFAULT NULL,
  `q63` char(1) DEFAULT NULL,
  `q64` char(1) DEFAULT NULL,
  `q65` char(1) DEFAULT NULL,
  `q66` char(1) DEFAULT NULL,
  `q67` char(1) DEFAULT NULL,
  `q68` char(1) DEFAULT NULL,
  `q69` char(1) DEFAULT NULL,
  `q70` char(1) DEFAULT NULL,
  `q71` char(1) DEFAULT NULL,
  `q72` char(1) DEFAULT NULL,
  `q73` char(1) DEFAULT NULL,
  `q74` char(1) DEFAULT NULL,
  `q75` char(1) DEFAULT NULL,
  `q76` char(1) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE `ClientCSSRSt`
  ADD PRIMARY KEY (`ID`);

ALTER TABLE `ClientCSSRSt`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

