CREATE TABLE ClientCANS (
  ID int(11) NOT NULL,
  ClientID int(11) DEFAULT NULL,
  CreateProvID int(11) DEFAULT NULL,
  CreateDate date DEFAULT NULL,
  ChangeProvID int(11) DEFAULT NULL,
  ChangeDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FormID varchar(12) DEFAULT NULL,
  Locked char(1) DEFAULT NULL,
  TestDate date DEFAULT NULL,
  q1 varchar(11) DEFAULT NULL,
  q2 varchar(11) DEFAULT NULL,
  q3 varchar(11) DEFAULT NULL,
  q4 varchar(11) DEFAULT NULL,
  q5 varchar(11) DEFAULT NULL,
  q6 varchar(11) DEFAULT NULL,
  q7 varchar(11) DEFAULT NULL,
  q8 varchar(11) DEFAULT NULL,
  q9 varchar(11) DEFAULT NULL,
  q10 varchar(11) DEFAULT NULL,
  q11 varchar(11) DEFAULT NULL,
  q12 varchar(11) DEFAULT NULL,
  q13 varchar(11) DEFAULT NULL,
  q14 varchar(11) DEFAULT NULL,
  q15 varchar(11) DEFAULT NULL,
  q16 varchar(11) DEFAULT NULL,
  q17 varchar(11) DEFAULT NULL,
  q18 varchar(11) DEFAULT NULL,
  q19 varchar(11) DEFAULT NULL,
  q20 varchar(11) DEFAULT NULL,
  q21 varchar(11) DEFAULT NULL,
  q22 varchar(11) DEFAULT NULL,
  q23 varchar(11) DEFAULT NULL,
  q24 varchar(11) DEFAULT NULL,
  q25 varchar(11) DEFAULT NULL,
  q26 varchar(11) DEFAULT NULL,
  q27 varchar(11) DEFAULT NULL,
  q28 varchar(11) DEFAULT NULL,
  q29 varchar(11) DEFAULT NULL,
  q30 varchar(11) DEFAULT NULL,
  q31 varchar(11) DEFAULT NULL,
  q32 varchar(11) DEFAULT NULL,
  q33 varchar(11) DEFAULT NULL,
  q34 varchar(11) DEFAULT NULL,
  q35 varchar(11) DEFAULT NULL,
  q36 varchar(11) DEFAULT NULL,
  q37 varchar(11) DEFAULT NULL,
  q38 varchar(11) DEFAULT NULL,
  q39 varchar(11) DEFAULT NULL,
  q40 varchar(11) DEFAULT NULL,
  q41 varchar(11) DEFAULT NULL,
  q42 varchar(11) DEFAULT NULL,
  q43 varchar(11) DEFAULT NULL,
  q44 varchar(11) DEFAULT NULL,
  q45 varchar(11) DEFAULT NULL,
  q46 varchar(11) DEFAULT NULL,
  q47 varchar(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

ALTER TABLE ClientCANS
  ADD PRIMARY KEY (ID);

ALTER TABLE ClientCANS
  MODIFY ID int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;

