#!/usr/bin/perl
use lib '/var/www/okmis/src/lib';
use DBI;
use DBForm;
############################################################################
# usage: cryptProv DBNAME=osage\&ForAgency=92
#        used to build the calendar users.txt file, according to agency
############################################################################
# Require Necessary Routines for this script to run.
##
$form = DBForm->parse;
if ( $form->{ForAgency} eq '' ) {
    print qq|No Agency given!\n|;
    print qq|specify: ForAgency=\n|;
    exit;
}
$dbh       = $form->dbconnect;
$sProvider = $dbh->prepare(
"select * from Provider left join UserLogin on UserLogin.UserID=Provider.ProvID where Provider.Active=1 and Provider.Type=4"
);
$sProvider->execute();
while ( my $rProvider = $sProvider->fetchrow_hashref ) {
    my $AgencyID = MgrTree->getAgency( $form, $rProvider->{ProvID} );
    warn qq|Provider: $rProvider->{ProvID}, $AgencyID\n|;
    if ( $AgencyID == $form->{ForAgency} ) {
        $c = crypt( $rProvider->{Password}, 'junk' );
        print
qq|$rProvider->{ProvID}\t$rProvider->{Name}\t$c\t$rProvider->{FName} $rProvider->{LName}\n|;
    }
}
exit;
