#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBForm;
use myDBI;
######################################################################
##
my $FACCT = $ARGV[0];
my $form = DBForm->new("DBNAME=$FACCT");
my $dbh = $form->dbconnect();
## one or the other, not both
## we need $TheID set for ProvID or ClientID
#main->setTable('Provider','where (Active=0 or Active is null)');
#main->setTable('Client','where (Active=0 or Active is null)');
main->setTable('Client','where ClientID=208','20208');
$form->complete();
exit;
###################################################################
sub setTable
{
  my ($self,$inTable,$with,$NewID) = @_;
  my $s=$dbh->prepare("select * from ${inTable} ${with}");
  $s->execute() || print qq|select * from ${inTable} ${with}\n|;;
  while ( my $r = $s->fetchrow_hashref )
  {
    my $RECID = myDBI->getTableConfig($inTable,'RECID');
    my $RECIDVAL = $r->{$RECID};
   ## print "delete from ${inTable} where ${RECID}=${RECIDVAL};\n";
    delete $r->{CreateDate};
    delete $r->{CreateProvID};
    delete $r->{RecDOLC};
    delete $r->{ChangeDate};
    delete $r->{ChangeProvID};
    $r->{$RECID} = $NewID;
    print DBA->genInsert($form,$inTable,$r) . ";\n";
    main->det($inTable,$RECIDVAL,$NewID,0);
  }
  $s->finish();
  return;
}
sub det
{
  my ($self,$inTable,$ID,$NewID,$Cnt) = @_;

  $Cnt++;
  foreach my $table ( myDBI->getDetTables($inTable) )
  {
    my $RECID = myDBI->getTableConfig($table,'RECID');
    my $HDRID = myDBI->getTableConfig($table,'DETAILID');
    my $s=$dbh->prepare("select * from ${table} where $HDRID=$ID");
#print qq|inTable=$inTable, table=$table, RECID=$RECID\n|;
    $s->execute() || print qq|select * from $table where $HDRID=$ID\n|;;
    my $rows=$s->rows;
    while ( my $r = $s->fetchrow_hashref )
    { 
      my $RECIDVAL = $r->{$RECID};
      my $spc = ' ' x $Cnt;
     ## print "${spc}delete from ${table} where ${RECID}=${RECIDVAL};\n";
      delete $r->{CreateDate};
      delete $r->{CreateProvID};
      delete $r->{RecDOLC};
      delete $r->{ChangeDate};
      delete $r->{ChangeProvID};
      delete $r->{$RECID};    # to go other levels would have to match this!!!
      $r->{$HDRID} = $NewID;
      print $spc . DBA->genInsert($form,$table,$r) . ";\n";
      ## only go 1 level...ID mismatch otherwise...main->det($table,$RECIDVAL,$Cnt);
    }
    $s->finish();
  }
}
