#!/bin/bash
case $1 in
   start) if [ "$2" != "httpd" ]; then /etc/rc.d/init.d/mysql start; fi
          sleep 1
          if [ "$2" != "sql" ]; then /etc/rc.d/init.d/httpd start; fi
          ;;
    stop) if [ "$2" != "sql" ]; then /etc/rc.d/init.d/httpd stop; fi
          if [ "$2" != "httpd" ]; then /etc/rc.d/init.d/mysql stop; fi
          ;;
esac
