#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use Accounts;
use myConfig;
use Cwd;
use Time::Local;
############################################################################
# usage: ExpTmpFiles            
#        Expire /tmp files over 4 hours old
############################################################################
# get the command name...
my ($pw,$cmd) = $0 =~ m/(.*\/)(.*)$/;
# the accounts to work with
my @ACCTS = $ARGV[0] eq 'test' ? Accounts->accts('test')
          : $ARGV[0] eq 'active' ? Accounts->accts('active')
          : $ARGV[0] eq 'live' ? Accounts->accts('live')
          : $ARGV[0] eq 'all' ? Accounts->accts('all')
          : scalar(@ARGV) ? @ARGV : Accounts->accts('active'); 
chdir(myConfig->cfg('WORKDIR'));
my $WWW = myConfig->cfg('WWW');
my $pwd=cwd();
print qq|${cmd}: Started: |.localtime().qq|\n|;
print qq|${cmd}: pwd=$pwd\n|;
print qq|======================================\n|;
my $now = time;
foreach my $acct ( @ACCTS )
{ print "Check $acct:\n"; &ExpireFiles("${WWW}/${acct}/tmp/*"); }
print qq|======================================\n\n|;
print qq|${cmd}: Completed: |.localtime().qq|\n|;
exit;
#####################################################################
sub ExpireFiles($)
{
  my ($Dir) = @_;
#print qq|ExpireFiles: ${Dir}\n|;
  my @TmpFiles = glob($Dir);
  my @ExpFiles = ();
  foreach $file ( @TmpFiles )
  {
    ($atime, $mtime) = (stat($file))[8,9];
    ($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime($mtime);
#print qq|$now, $atime, $mtime\n|;
#print qq|($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst)\n|;
#my $diff = $now-$mtime; print qq|${file}: ${now}, ${mtime}, diff=${diff}\n|;
    # 14400 = 4 hours old...
    if ( $now-$mtime > 14400 )
    { print "Expire: $file\n"; push(@ExpFiles, $file); }
  }
  unlink(@ExpFiles);
  return(1);
}
#####################################################################
