#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use DBForm;
use DBA;
############################################################################
my $form = DBForm->new();
  my $table = 'ClientVitalSigns';
  my $dbh = $form->dbconnect();
  my $s = $dbh->prepare("select * from ${table} order by ClientID");
  $s->execute() || $form->dberror("fixit:: select ${table}");
  while ( my $r = $s->fetchrow_hashref )
  {
    PostUpd->updClientVitalSigns($form,$r->{'ID'});
  }
  $s->finish();
$form->complete();
exit;
############################################################################
