#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use DBForm;
use DBA;
############################################################################
# This routine moves the ICN transaction from one TrID to another
#  and changes the 'moved to' TrID to Denied.
#  used to fix the void/recoupment from one note to another.
############################################################################
my $form = DBForm->new();
my $dbh = $form->dbconnect();
my $today = $form->{'TODAY'};
my $TransID = $form->{'TransID'};
my $TrID = $form->{'TrID'};
my $sTreatment=$dbh->prepare("select Treatment.* from NoteTrans left join Treatment on Treatment.TrID=NoteTrans.TrID where NoteTrans.ID=?");
$sTreatment->execute($TransID) || $form->dberror("fixICN: select Treatment = $TransID");
my $rTreatment = $sTreatment->fetchrow_hashref;
my $TransTrID = $rTreatment->{'TrID'};
my $ContDate = $rTreatment->{'ContLogDate'};
$sTreatment->finish();
my $sMove = $dbh->prepare("update NoteTrans set TrID='${TrID}' where ID='${TransID}'");
print qq|  move TransID:${TransID} (${ContDate}) to TrID:${TrID}.\n|;
$sMove->execute() || $form->dberror("Move: ${TransID} to ${TrID}");
$sMove->finish();
my $sUpdate = $dbh->prepare("update Treatment set BillStatus='6',StatusDate='${today}',DenDate='${today}',DenCode='129',RecDate=NULL where TrID='${TrID}'");
print qq|  deny TrID:${TrID}.\n|;
$sUpdate->execute() || $form->dberror("Deny: ${TrID}");
$sUpdate->finish();
if ( $form->{'Reconcile'} )    # reconcile? the Transaction moved from?
{
  print qq|  reconcile TrID:${TransTrID} (TransID:${TransID})\n|;
# the Note...
  my $sReconcile=$dbh->prepare("update Treatment set BillStatus=5,StatusDate='${today}',RecDate='${today}',AmtDue=0,CIPDate=NULL, DenDate=NULL, DenCode=NULL, COPLDate=NULL where TrID='${TransTrID}'");
  $sReconcile->execute() || $form->dberror("fixICN: Reconcile ${TransTrID}");
  $sReconcile->finish();
}
if ( $form->{'Scholarship'} )    # reconcile? the Transaction moved from?
{
  print qq|  scholarship TrID:${TransTrID} (TransID:${TransID})\n|;
# the Note...
  my $sScholarship=$dbh->prepare("update Treatment set BillStatus=4,StatusDate='${today}',RecDate='${today}',AmtDue=0,CIPDate=NULL, DenDate=NULL, DenCode=NULL, COPLDate=NULL where TrID='${TransTrID}'");
  $sScholarship->execute() || $form->dberror("fixICN: Scholarship ${TransTrID}");
  $sScholarship->finish();
}
$form->complete();
############################################################################
exit;
