#!/usr/bin/perl
use lib 'C:/xampp/htdocs/src/lib';
use DBI;
use DBForm;
use DBA;
use uBill;
############################################################################
my $form = DBForm->new();
main->fixit( $form, 'ClientPHQ9', 1, 9 );
$form->complete();
exit;
############################################################################
sub fixit {
    my ( $self, $form, $table, $beg, $end ) = @_;
    my $fld  = 'q';                  # prefix of rPHQ field name.
    my $dbh  = $form->dbconnect();
    my $sPHQ = $dbh->prepare(
        "select * from ${table} where ClientID=56870 order by ClientID");
    $sPHQ->execute() || $form->dberror("fixPHQ:: select ${table}");
    while ( my $rPHQ = $sPHQ->fetchrow_hashref ) {
        my $ClientID = $rPHQ->{'ClientID'};
        my $TestDate = $rPHQ->{'TestDate'};
        print qq|ClientID=$ClientID, TestDate=${TestDate}...\n|;
        my $sTreatment = $dbh->prepare(
"select * from Treatment where ClientID=? and ContLogDate=? and (SCID=1234 or SCID=1234)"
        );
        $sTreatment->execute( $ClientID, $TestDate )
          || $form->dberror("select Treatment: ${ClientID} ${TestDate}");
        if ( my $rTreatment = $sTreatment->fetchrow_hashref ) {
            my $TrID = $rTreatment->{'TrID'};
            print qq|  set TrID=${TrID}\n|;
            my $sUpdate = $dbh->prepare(
                "update ${table} set TrID='${TrID}' where ID='$rPHQ->{ID}'");
            $sUpdate->execute()
              || $form->dberror("fixPHQ: Update ${TrID} ${table}: $rPHQ->{ID}");
            $sUpdate->finish();
        }
    }
    $sPHQ->finish();
    return ();
}
############################################################################
