#!/bin/bash
find . -type f -exec grep -Hs "$1" {} \;
##find . -type f -exec grep -Hn '[^[:print:]]' {} \;    # find non-print chars
##find . -type f -exec grep -Hn '[[:cntrl:]]' {} \;     # find control chars
