#!/usr/bin/perl
use lib '/var/www/okmis/src/lib';
use DBUtil;

############################################################################
my $APIKEY = DBUtil->genToken(24);
print $APIKEY. "\n";
exit;
