#!/usr/bin/perl
use lib 'C:/xampp/htdocs/src/lib';
use DBUtil;

############################################################################
my $APIKEY = DBUtil->genToken(24);
print $APIKEY. "\n";
exit;
