#!/usr/bin/perl
use lib 'C:/xampp/htdocs/src/lib';
use DBI;
use DBForm;
use MgrTree;
use DBA;

############################################################################
$form = DBForm->new;

############################################################################
my $dbh = $form->dbconnect;
$qProvider = qq|select * from Provider where Active=1|;
my $sProvider = $dbh->prepare($qProvider);
$sProvider->execute() || $form->dberror($qProvider);
while ( $rProvider = $sProvider->fetchrow_hashref ) {
    $ProvID = $rProvider->{ProvID};
    $Name   = $rProvider->{Name};
    $LName  = $rProvider->{LName};
    $FName  = $rProvider->{FName};
    my $ClinicID = MgrTree->getAgency( $form, $ProvID );
    if ( $ClinicID == 215 ) {
        $NewPassword = DBA->genPassword();
        print "## ${Name}\t${LName}\t${FName}\t${ProvID}\t${NewPassword}\n";
        print
"update UserLogin set Password='${NewPassword}' where UserID='${ProvID}';\n";
    }
}
$sProvider->finish();
exit;
