#!/bin/bash
#--------------------
if [ -f /etc/config.csi ]; then
   . /etc/config.csi
else
   echo -e "\nServices not installed!"
   exit 1
fi
LogFile=${LOGDIR}/${CMD}
#--------------------
TmpFile=/tmp/$$
DB=$1
SCID=$2
#-------------------------
Usage()
{
   echo $1
   echo
   echo "Usage: ${CMD} database statement"
   echo
   exit
}
#-------------------------
if [ -z "${SCID}" ]; then Usage "No SCID!"; fi
if [ ! -d ${DBDIR}/${DB} ]; then Usage "Invalid database!"; fi
  echo "select xSC.SCID, xSC.SCNum, xSCRates.UnitLbl, xSCRates.ServiceRate, xSCRates.HrsPerUnit, xSCRates.RatePct, xSCRates.EffDate, xSCRates.ExpDate from xSC left join xSCRates on xSCRates.SCID=xSC.SCID where xSC.SCID=$SCID order by xSCRates.EffDate;" > ${TmpFile}.in
  ${DBCMD} ${DB} < ${TmpFile}.in
  rm ${TmpFile}.in
