#!/usr/bin/perl
use lib '/var/www/okmis/src/lib';
use DBI;
use DBForm;
use DBA;

############################################################################
my $form  = DBForm->new();
my $dbh   = $form->dbconnect();
my $myID  = $form->{'myID'};
my $lock  = $form->{'lock'};
my $table = $form->{'table'};
if ( $myID eq '' ) { print qq|\nmyID cannot be null!\n\n|; exit; }

my $q = '';
if ( $table eq 'ClientPrAuth' ) {
    $q =
"update ClientPrAuth left join PDDom on PDDom.PrAuthID=ClientPrAuth.ID set ClientPrAuth.Locked=${lock},PDDom.Locked=${lock} where ClientPrAuth.ID='${myID}'";
}
else { print qq|\n${table} not supported!\n\n|; exit; }

print qq|${q}\n|;
my $sLock = $dbh->prepare($q);
$sLock->execute()
  || $form->dberror("lockunlock: lock=${lock} ${table}: ${myID}");
$sLock->finish();
my $s = $dbh->prepare(
"update ClientPrAuthCDC set CDCKey=NULL,Status='New',StatusDate='$form->{'TODAY'}' where ClientPrAuthID='${myID}'"
);
$s->execute() || $form->dberror("lockunlock: NULL CDCKey ${table}: ${myID}");
my $s =
  $dbh->prepare("update ClientPrAuth set PAnumber=NULL where ID='${myID}'");
$s->execute() || $form->dberror("lockunlock: NULL PAnumber ${table}: ${myID}");
$s->finish();
$form->complete();
exit;
############################################################################
