#!/bin/bash
# kls, daily 11/11/2008
# ------------------------------------
if [ -f /etc/config.csi ]; then
   . /etc/config.csi
else
   echo -e "\nServices not installed!"
   exit 1
fi
ACCTS=$(${MISBIN}/accts LIVE)
ACCTS=mms
# ------------------------------------
for ACCT in $ACCTS; do
  if [ -d ${WWW}/${ACCT}/Provider/EFiles/835 ]; then
    cd ${WWW}/${ACCT}/Provider/EFiles/835
    echo "check ${ACCT}/Provider/EFiles/835..."
    for fn in $(/bin/ls -1 *.pdf 2>/dev/null); do
      mv -v ${fn} /home/okmis/www/forms/printing/${fn}
    done
  fi
done
