#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use DBForm;
use DBUtil;
############################################################################
# ./moveEligible
#   only kkeps the last month of records, move all others to EligibleHist
############################################################################
# get the command name...
my ($pw,$cmd) = $0 =~ m/(.*\/)(.*)$/;
print qq|#${cmd}: Started |.localtime().qq|\n|;
my $form = DBForm->new();
my $dbh = $form->dbconnect();
my $List = ();
my $totcnt = 0;
my $sEligible = $dbh->prepare("select distinct ClientID,FromDate from Eligible order by ClientID,FromDate");
$sEligible->execute() || $form->dberror("moveEligible: select for $beforeDate");
while ( my $rEligible = $sEligible->fetchrow_hashref )
{ $List->{$rEligible->{'ClientID'}} = $rEligible->{'FromDate'}; }
$sEligible->finish();
foreach my $ClientID ( sort keys %{$List} )
{
  my $BeforeDate=$List->{$ClientID};
  print qq|Move: ${ClientID}/${BeforeDate}...\n|;
  my $cnt = main->move($form,$ClientID,$BeforeDate);
  print qq|${cnt} processed.\n|;
  $totcnt+=$cnt;
}
print qq|${totcnt} processed.\n|;
print qq|#${cmd}: Completed |.localtime().qq|\n|;
$form->complete();
exit;
############################################################################
sub move
{
  my ($self,$form,$CID,$bDate) = @_;
 
  my $dbh = $form->dbconnect();
  my $sDelete = $dbh->prepare("delete from Eligible where ID=?");
  my $Cnt=0;
  my $sEligible = $dbh->prepare("select * from Eligible where ClientID=? and FromDate<? order by FromDate");
  $sEligible->execute($CID,$bDate) || $form->dberror("select for $CID,$bDate");
  while ( my $r = $sEligible->fetchrow_hashref )
  {
    $Cnt++;
    my $qEligibleHist = DBA->genInsert($form,'EligibleHist',$r);
    $sEligibleHist = $dbh->prepare($qEligibleHist);
    $sEligibleHist->execute() || $form->dberror("moveEligible: insert error $r->{ID}");
    $sEligibleHist->finish();
    $sDelete->execute($r->{ID}) || $form->dberror("moveEligible: delete error $r->{ID}");
  }
  $sEligible->finish();
  $sDelete->finish();
  return($Cnt);
}
##########################################################
