#!/bin/bash
# kls, daily 11/4/08
# ------------------------------------
if [ -f /etc/config.csi ]; then
   . /etc/config.csi
else
   print "\nServices not installed!"
   exit 1
fi
# ------------------------------------
  print "\n======================================"
  print "${CMD} Started: $(date)"
# ------------------------------------
# in directory.
  iDir=${MAINDIR}/officeally/receive
  if [ ! -d ${iDir} ]; then
    print "\nError NO ${iDir}!!!"
    exit 1
  fi
  cd ${iDir}
  sDir=${MAINDIR}/officeally/received
  if [ ! -d ${sDir} ]; then
    print "\nError NO ${sDir}!!!"
    exit 1
  fi
# ------------------------------------
# process ERA files
  for file in $(/usr/bin/find *ERA_STATUS_4010*.txt -type f); do
    print "\nProcess ${file} pwd=$(pwd)..."
    ${MISSBIN}/parseERA ${file}
    mv -v ${file} ${sDir}/${file}
  done
  for file in $(/usr/bin/find *ERA_STATUS_5010*.txt -type f); do
    print "\nProcess ${file} pwd=$(pwd)..."
    ${MISSBIN}/parseERA ${file}
    mv -v ${file} ${sDir}/${file}
  done
# ------------------------------------
  print "\n${CMD} Complete: $(date)"
  print "======================================\n"
# ------------------------------------
