#!/bin/bash
# kls, daily 11/4/08
# ------------------------------------
if [ -f /etc/config.csi ]; then
   . /etc/config.csi
else
   print "\nServices not installed!"
   exit 1
fi
# ------------------------------------
  print "\n======================================"
  print "${CMD} Started: $(date)"
# ------------------------------------
# in directory.
  iDir=${MAINDIR}/availity/received
  if [ ! -d ${iDir} ]; then
    print "\nError NO ${iDir}!!!"
    exit 1
  fi
  cd ${iDir}
# ------------------------------------
# process EVT files
  for file in $(/usr/bin/find EBT* -type f -mtime -1); do
    print "\nProcess ${file} pwd=$(pwd)..."
    ${MISSBIN}/parseEBT ${file}
  done
# ------------------------------------
  print "\n${CMD} Complete: $(date)"
  print "======================================\n"
# ------------------------------------
