#!/usr/bin/perl
use lib 'C:/xampp/htdocs/src/lib';
use DBI;
use DBForm;
use DBA;
use Time::Local;

############################################################################
# usage: prtAmtDue DBNAME=xxxx\&ClientID=id
############################################################################
$form = DBForm->new;
my $dbh    = $form->dbconnect;
my $AmtDue = 0;
my $dbh    = $form->dbconnect;
my $q      = qq|select * from Treatment where AmtDue > 0 |;
$q .= qq| and TrID=$form->{TrID} |         if ( $form->{TrID} );
$q .= qq| and ClientID=$form->{ClientID} | if ( $form->{ClientID} );
$q .= qq| order by ContLogDate|;
my $s = $dbh->prepare($q);
$s->execute();

while ( my $r = $s->fetchrow_hashref ) {
    $AmtDue += $r->{AmtDue};
    print
      qq|$r->{TrID}, $r->{BillDate}, $r->{RecDate}, $r->{AmtDue}, $AmtDue\n|;
}
$s->finish();
$AmtDue = sprintf( "%.2f", $AmtDue );
print qq|AmtDue=$AmtDue\n|;
exit;
