#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use myForm;
use myDBI;
use Rollup;
############################################################################
# usage: setClientRollup DBNAME=db&[ClientID=cid]
############################################################################
# get the command name...
my ($pw,$cmd) = $0 =~ m/(.*\/)(.*)$/;
print qq|#${cmd}: Started |.localtime().qq|\n|;
my $form = myForm->new();
my $dbh = myDBI->dbconnect($form->{'DBNAME'});
# for only 1 Client??
my $qClient = $form->{ClientID} ? qq|select * from Client where ClientID='$form->{ClientID}' order by ClientID| : qq|select * from Client order by ClientID|;
#print qq|qClient=${qClient}\n|;
my $sClient = $dbh->prepare($qClient);
$sClient->execute() || $form->dberror($qClient);
while ( my $rClient = $sClient->fetchrow_hashref )
{
  my $ClientID=$rClient->{'ClientID'};
  print qq|  Process ClientID=${ClientID}...\n|;
  ##
  # make sure the directory exists
  ##
  my $HomePath = qq|/Client/EDocs/${ClientID}|;
  my $RootPath = $form->{DOCROOT} . ${HomePath};
  system("/bin/mkdir -pm 777 ${RootPath}");

  my $IDs;
  $IDs = Rollup->edocs($form,$ClientID,'ClientAdmit','2017-01-01');
  $IDs = Rollup->edocs($form,$ClientID,'ClientAdmit');
  $IDs = Rollup->edocs($form,$ClientID,'ClientTrPlan');
  $IDs = Rollup->edocs($form,$ClientID,'ClientPrAuth');

  # CHANGE:START adding more notes

  Rollup->edocs($form,$ClientID,'ClientPrAuthCDC');
  Rollup->edocs($form,$ClientID,'ClientLabs');
  Rollup->edocs($form,$ClientID,'ClientCARSReview');
  Rollup->edocs($form,$ClientID,'ClientEDocs');
  Rollup->edocs($form,$ClientID,'PDMed');
  Rollup->edocs($form,$ClientID,'ClientRiskAssessment');

  Rollup->edocs($form,$ClientID,'ClientPHQ');
  Rollup->edocs($form,$ClientID,'ClientPHQ15');
  Rollup->edocs($form,$ClientID,'ClientPHQ2');
  Rollup->edocs($form,$ClientID,'ClientPHQ4');
  Rollup->edocs($form,$ClientID,'ClientPHQ9');
  Rollup->edocs($form,$ClientID,'ClientTPHQ9');
  Rollup->edocs($form,$ClientID,'ClientPHQBrief');
  Rollup->edocs($form,$ClientID,'ClientPHQSADS');

  Rollup->edocs($form,$ClientID,'ClientTASI');
  Rollup->edocs($form,$ClientID,'ClientASAM');

  Rollup->edocs($form,$ClientID,'ClientACE');
  Rollup->edocs($form,$ClientID,'ClientGAD7');
  Rollup->edocs($form,$ClientID,'ClientBasis32');
  Rollup->edocs($form,$ClientID,'ClientASI');

  my $TrIDs = Rollup->Notes($form,$ClientID);
  my $cnt = split(' ',$TrIDs);
#warn qq|Progress: cnt=$cnt\n|;
  $IDs = Rollup->edocs($form,$ClientID,'ClientDischarge');
}
myDBI->cleanup();
print qq|#${cmd}: Complete |.localtime().qq|\n\n|;
############################################################################
exit;
