#!/usr/bin/perl
use lib 'C:/xampp/htdocs/src/lib';
use Accounts;
use DBI;
use DBForm;
use DBA;
############################################################################
# This routine set the Rank value in Provider's Credentials if null.
############################################################################
my $qUpdate      = qq|update Credentials set Rank=? where ID=?|;
my $qCredentials = qq|select * from Credentials where Rank is null|;
my $form;
my $dbh;
my @DBS = scalar(@ARGV) ? @ARGV : Accounts->dbs('active');
foreach my $dbname (@DBS) {
    print qq|Database: $dbname\n|;
    $form = DBForm->new("DBNAME=$dbname");
    $dbh  = $form->dbconnect();
    my $sUpdate      = $dbh->prepare($qUpdate);
    my $sCredentials = $dbh->prepare($qCredentials);
    $sCredentials->execute() || $form->dberror($qCredentials);
    my $cnt = $sCredentials->rows;
    while ( $rCredentials = $sCredentials->fetchrow_hashref ) {
        my $Rank = DBA->getxref( $form, 'xCredentials', $rCredentials->{CredID},
            'Rank' );
        $Rank = 99 if ( $Rank eq '' );
        $sUpdate->execute( $Rank, $rCredentials->{ID} )
          || $form->dberror($qUpdate);

#print qq|update to ${Rank} ($rCredentials->{ProvID},$rCredentials->{CredID},$rCredentials->{Rank},$rCredentials->{ID})\n|;
        $cnt++;
    }
    $form->complete();
    print qq|$cnt rows updated.\n|;
}
exit;
############################################################################
