#!/bin/bash
#--------------------
if [ -f /etc/config.csi ]; then
   . /etc/config.csi
else
   echo -e "\nServices not installed!"
   exit 1
fi
LogFile=${LOGDIR}/${CMD}
#--------------------
TmpFile=/tmp/$$
DB=$1
#-------------------------
Usage()
{
   echo $1
   echo
   echo "Usage: ${CMD} database statement"
   echo
   exit
}
#-------------------------
if [ ! -d ${DBDIR}/${DB} ]; then Usage "Invalid database!"; fi
  echo "select Provider.ProvID, Provider.Active, Provider.LName, Provider.FName, Provider.DOB, Provider.SSN, Provider.Email from Provider order by LName;" > ${TmpFile}.in
  ${DBCMD} ${DB} < ${TmpFile}.in
  rm ${TmpFile}.in
