#!/usr/bin/perl
use lib '/home/okmis/mis/src/lib';
use DBI;
use myForm;
use myDBI;
use Rollup;

############################################################################
# usage: updateSCRATES "DBNAME=db"
############################################################################

# get the command name...
my ($pw,$cmd) = $0 =~ m/(.*\/)(.*)$/;
print qq|#${cmd}: Started |.localtime().qq|\n|;
my $form = myForm->new();
my $dbh = myDBI->dbconnect($form->{'DBNAME'});

print qq|  Database Selected = $form->{'DBNAME'}...\n|;

my $EB = $dbh->prepare("SELECT * FROM `Eligible` WHERE PlanDescr = 'SoonerSelect' and BenefitDescr = 'Primary Care Provider' GROUP BY ClientID");

my $xInsurance = $dbh->prepare("SELECT * FROM xInsurance WHERE Name Like ?");
my $sClInsurance = $dbh->prepare("SELECT * FROM Insurance WHERE InsID=? and ClientID=?");

my $upd_cl_insurance = $dbh->prepare("Update Insurance SET Priority=2 WHERE ClientID=? and Priority=1 and InsID = '100'");
my $upd_cl_insurance_2 = $dbh->prepare("Update Insurance SET Priority=1 WHERE ClientID=? and InsID=?");

$EB->execute();

while(my $rEB = $EB->fetchrow_hashref) {
  my $ClientID = $rEB->{'ClientID'};
  my $OtherInsName = $rEB->{'OtherInsName'};

  print qq|  Eligible ClientID = ${ClientID}...\n|;
  
  # Set OtherInsName to "Humana HEALTHY HORIZONS" if it matches the pattern
  print qq|  Eligible OtherInsName = ${OtherInsName}...\n|;

  if ($OtherInsName =~ /HUMANA HEALTHY HORIZONS/) {
    $OtherInsName = "HUMANA HEALTHY HORIZONS";
    print qq|  Using OtherInsName: $OtherInsName\n|;
  } 
  $xInsurance->execute("%$OtherInsName%");

  my $rInsurance = $xInsurance->fetchrow_hashref;
  my $InsID = $rInsurance->{ID};

  next if(!$InsID);

  print qq|  rInsurance InsID = ${InsID}...\n|;

  print qq|  Update Current Primary Insurance to Secondary\n|;
  $upd_cl_insurance->execute($ClientID);

  $sClInsurance->execute($InsID, $ClientID);
  if(my $rClInsurance = $sClInsurance->fetchrow_hashref) {
    print qq|  Set The MCO $OtherInsName as Primary Insurance\n|;

    $upd_cl_insurance_2->execute($ClientID, $InsID);
  }
}

# Finish all statement handles
$EB->finish();
$xInsurance->finish();
$sClInsurance->finish();
$upd_cl_insurance->finish();
$upd_cl_insurance_2->finish();


# ADD TWO COLUMNS AgencyStatus and TermDate to Provider Control Table

# my $alt_1 = $dbh->prepare("ALTER TABLE `ProviderControl` ADD `AgencyStatus` CHAR(1) NOT NULL DEFAULT '1' AFTER `CAQH`");
# my $alt_2 = $dbh->prepare("ALTER TABLE `ProviderControl` ADD `TermDate` DATE NULL DEFAULT NULL AFTER `AgencyStatus`");

# $alt_1->execute();
# $alt_2->execute();


# $alt_1->finish();
# $alt_2->finish();

# Disconnect the database handle
$dbh->disconnect();

myDBI->cleanup();
print qq|#${cmd}: Complete |.localtime().qq|\n\n|;
############################################################################
exit;
