#!/bin/bash
# kls, daily 2/2/98, 11/26/2001
# ------------------------------------
if [ -f /etc/config.csi ]; then
   . /etc/config.csi
else
   print "\nServices not installed!"
   exit 1
fi
# ------------------------------------
#find . -type f -name "CDC.cgi" |
cat fixp.in |
while read fn; do
  echo "convert: ${fn}"
  sed "s;DBForm->genLink;myForm->genLink;" ${fn} > new
  mv new ${fn}
done
